### ISSUE TITLE
[Bug]캐릭터가 공격하지 못하는 상황

### ISSUE THREAD

**Issue by seonghyun0719** [anMois/Project_F#49]
- 발생 개요
캐릭터가 이동,점프시 공격키를 눌러도 공격을 하지 않고 멈춰버림
- 발생 방법, 이미지
기본 움직이 또는 점프를 하며 공격키(좌클릭) 누를 시 움직임이 그 자리에 멈춰버림 
좌클릭을 꾹 누르고 있을 시 움직이지 않음

**Comment by Potato0328** [comment]
마우스 길게 누를 시 움직임 멈춤으로 인하여 정지여서 수정하고 말씀 드리겠습니다.

**Comment by Potato0328** [comment]
수정 완료 했습니다.

**Comment by EagleLoo** [comment]
바닥에 있어도 울퉁불퉁해서 isGround가 활성화 안되더라구요.
그래서 투명한 Plane 오브젝트에 Ground 태그 다니깐 잘 공격하더라구요.
내일 모든 맵 다 적용해서 업데이트 하겠습니다.
