### ISSUE TITLE
[Bug]좌클릭 광클 시 공격이 나가지 않음

### ISSUE THREAD

**Issue by seonghyun0719** [anMois/Project_F#50]
- 발생 개요
움직이거나 점프 하면서 좌클릭 연타 시 공격이 나가지않음
- 발생 방법, 이미지
- 움직이거나,점프 하면서 좌클릭을 연타하면 공격이 딱 한발 나가게 되는데
 그 이후부터는 가만히 서서 공격을해도 공격이 나가지 않음 
  점프 하면서 좌클릭 광클 시 해당 버그가 풀리기는 함

**Comment by Potato0328** [comment]
확인 했습니다.
수정 후 말씀 드리겠습니다.

**Comment by EagleLoo** [comment]
요것도 바닥에 투명한 Plane 까니깐 연타 잘 되더라구요.
이거는 제가 닫겠습니다.
