### ISSUE TITLE
[Bug] 점프 모션이 풀리지 않는 버그

### ISSUE THREAD

**Issue by seonghyun0719** [anMois/Project_F#51]
- 발생 개요
-점프를 하면서 돌아 다니다가 나무와 돌 같은 평평하지 않은 오브젝트에 충돌 시 점프 모션이 풀리지 않음
- 발생 방법, 이미지
점프를 하고 착지할떄 나무,상자, 돌 과 같은 뽀족하거나 평평하지 않은 오브젝트에 충돌 시 점프 모션이 풀리지 않음(일정 시간이 지나면 풀리긴 함)
![image](https://github.com/user-attachments/assets/a2d2d94a-6c21-4554-b4f5-c36ccc83dc96)

**Comment by Potato0328** [comment]
확인 했습니다.
수정 후 말씀 드리겠습니다.

**Comment by Potato0328** [comment]
수정 완료 했습니다.

**Comment by EagleLoo** [comment]
아 공격 이슈때 말씀드리긴 했는데 투명한 Plane 설치해서 해당 이슈가 더 발생안하도록 작업하겠습니다.
