### ISSUE TITLE
[Bug]가만히 있는데도 조금식 미끄러짐

### ISSUE THREAD

**Issue by seonghyun0719** [anMois/Project_F#52]
- 발생 개요
가만히 있는데도 캐릭터가 내리막길에 있는것처럼 조금씩 -x축 방향으로미끄러짐
- 발생 방법, 이미지
가민히 캐릭터를 놔두면 됨

**Comment by Potato0328** [comment]
확인 했습니다.
수정 후 말씀 드리겠습니다.

**Comment by Potato0328** [comment]
이것은 물체에 대한 힘으로 인하여 밀리는 것으로 보시면 될 것 같습니다.

**Comment by EagleLoo** [comment]
네 확인했습니다.
