### ISSUE TITLE
[Bug]벽에다가 비비면서 점프 시 계속 점프가 됨

### ISSUE THREAD

**Issue by seonghyun0719** [anMois/Project_F#53]
- 발생 개요
캐릭터가 벽에 붙어있을때 벽에 붙어서 점프를 한면 기존의 점프 3번을 무시하고 
벽에 붙어만 있다면 계속해서 점프가 가능함 
- 발생 방법, 이미지
1.캐릭터를 벽 근처에 이동 시킴
2.점프를 하면서 벽에 비빈다.
3.벽에 비비면서 점프키를 계속해서 누른다

-예상 원인
벽에 튀어나온 부분까지도 바닥으로 인식해서 점프 횟수가 초기화 되는것 같음

**Comment by Potato0328** [comment]
확인 했습니다.
수정 후 말씀 드리겠습니다.

**Comment by Potato0328** [comment]
수정 완료 했습니다.

**Comment by EagleLoo** [comment]
넵 확인했습니다!
