### ISSUE TITLE
[Bug] 메인 메뉴에서 정지패널 활성화

### ISSUE THREAD

**Issue by anMois** [anMois/Project_F#58]
## 발생 개요
- 메인 화면 중 도감 페이지와 메뉴얼 페이지에서 esc를 입력 시 정지 패널이 활성화 됨

## 발생 방법, 이미지
- 메인 화면 중 도감 페이지와 메뉴얼 페이지에서 esc를 입력 시 정지 패널이 활성화 됨
- 정지 패널에서 버튼 입력 시 기존에 있던 패널을 무시하고 정지 패널에 있던 버튼으로 활성화됨

**Comment by leeyunjeong010422** [comment]
확인했습니다 수정하겠습니다..........

**Comment by leeyunjeong010422** [comment]
버그 수정 완료하였습니다
