### ISSUE TITLE
[Bug] 메인 화면에서 상태창이 열리는 버그

### ISSUE THREAD

**Issue by anMois** [anMois/Project_F#65]
## 발생 개요
-  게임 시작 화면인 메인 화면에서 상태창이 열립니다.

## 발생 방법, 이미지
- 메인 화면에서 `i`입력 시 상태창이 열림

**Comment by leeyunjeong010422** [comment]
확인했습니다 수정하겠습니다

**Comment by leeyunjeong010422** [comment]
수정되었습니다
